### ISSUE TITLE
Instructions on README.MD page should read my_api_project not my-api-project

### ISSUE THREAD

**Issue by nissan** [popov1024/httpapi-template-csharp#2]
I was following the README.MD and when I hit the step to 
`docker-compose up --build -d`
I kept hitting the error
```
/bin/bash -c "dotnet restore ./src/my_api_project.csproj && dotnet publish ./src/my_api_project.csproj -c Release -o ./obj/Docker/publish"
MSBUILD : error MSB1009: Project file does not exist.
Switch: ./src/my_api_project.csproj
```
It seems like the generator does not like dashes (-) in folder names. Switching to underscore(_) solved this issue. The introduction documentation should reflect this.

Solution:
Lines in instruction that read
```
mkdir my-api-project
cd my-api-project
```

should be changed to read
```
mkdir my_api_project
cd my_api_project
```

**Comment by popov1024** [comment]
Thank you
