### ISSUE TITLE
docker-compose fails on project install

### ISSUE THREAD

**Issue by weklund** [popov1024/httpapi-template-csharp#4]
Trying out .NET for the 1st time on a Mac and getting this issue.  It's odd because hello_world_demo.csproj clearly exists.

Also, thanks for a template with docker!

```
$ docker-compose -f docker-compose.ci.build.yml up --build
Starting helloworlddemo_ci-build_1 ... done
Attaching to helloworlddemo_ci-build_1
ci-build_1  | MSBUILD : error MSB1009: Project file does not exist.
ci-build_1  | Switch: ./src/hello_world_demo.csproj
helloworlddemo_ci-build_1 exited with code 1
```

Here's my dotnet info:

```
$ dotnet --info
.NET Command Line Tools (2.1.101)

Product Information:
 Version:            2.1.101
 Commit SHA-1 hash:  6c22303bf0

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.101/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.6
  Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d
```

**Comment by weklund** [comment]
So if the directory you're running `dotnet new httpapi` has dashes instead of underscores, the template won't create the right files.

I think in the docker-compose it's looking for `hello_world_demo.csproj` where it's actually `hello-world-demo-csproj`

There's a mismatch in a few other places as well.

**Comment by popov1024** [comment]
https://github.com/dotnet/templating/issues/1168
